version: "3"
services:
  front:
    image: node:21
    networks:
      - net1
    build:
      context: ./front
      args:
        # Отредактируйте эти параметры, если ваш локальный пользователь имеет другие UID и GID.
        ARG_UID: 1000
        ARG_GID: 1000
    ports:
      - 5000:3000
    volumes:
      - ./front:/var/www/front

  back:
    image: node:18
    networks:
      - net1
    build:
      context: ./back
      args:
        # Отредактируйте эти параметры, если ваш локальный пользователь имеет другие UID и GID.
        ARG_UID: 1000
        ARG_GID: 1000
    ports:
      - 5001:1000
    volumes:
      - ./back:/var/www/back
    environment:
      PORT: 1000
      RABBIT_URL: amqps://guest:guest@rabbitmq:15672
      DB_URL: mongodb://root:root@mongo:27017/?authMechanism=DEFAULT

  mongo:
    image: mongo
    networks:
      - net1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db:/data/db
    ports:
      - 5002:27017

  mongo-express:
    image: mongo-express
    networks:
      - net1
    restart: always
    ports:
      - 5003:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  db:

networks:
  net1:
    driver: bridge
